---

- name: Ensure apt works with HTTPS and certificates are installed and kernel extrax
  apt:
    pkg="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time=3600
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add apt repo GPG
  apt_key:
    id="{{ dockerhost_id }}"
    url="{{ docker_gpg_url }}"

- name: Add docker apt repo
  apt_repository:
    repo="deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    update_cache="yes"

- name: Purge the old repo (lxc-docker)
  apt:
    pkg="lxc-docker"
    state="absent"
    purge="true"
