---

#https://docs.docker.com/engine/installation/linux/ubuntulinux/

- name: Add docker group
  group: 
    name="{{ dockerhost_group }}"
    system="True"
    state="present"

- name: Include apt tasks
  include: apt.yml

- name: Include docker-py
  include: docker-py.yml
  when: docker_install_py_module

- name: Install docker engine
  apt:
    pkg="docker-engine"

- name: Include docker-compose.yml
  include: docker-compose.yml
  when: docker_compose_install

- name: Include docker conf
  template: 
    src=docker_conf_ubuntu_14.04.j2
    dest=/etc/default/docker
  notify: 
    - restart docker

- name: Ensure docker is running and starts by default
  service: 
    name="docker"
    state="started"
    enabled=True
