---

#https://docs.docker.com/engine/installation/linux/ubuntulinux/

- name: Add docker group
  group:
    name: "{{ dockerhost_group }}"
    system: True
    state: present

- name: Apt tasks
  include: apt.yml

- name: Include docker-py
  include: docker-py.yml
  when: docker_install_py_module

- name: Install docker engine
  apt:
    pkg: "docker-ce"

- name: Include docker-compose.yml
  include: docker-compose.yml
  when: docker_compose_install

- name: Create docker conf
  template:
    src: docker_conf.j2
    dest: /etc/default/docker
  when: ansible_service_mgr != 'systemd'
  notify:
  - restart docker

- name: Create docker systemd unit file
  template:
    src: docker_systemd_service.j2
    dest: /etc/systemd/system/docker.service
  when: ansible_service_mgr == 'systemd'
  notify:
  - restart docker systemd

- name: Create docker daemon config file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
  - restart docker systemd

- meta: flush_handlers

- name: Ensure docker is running and starts by default
  service:
    name: docker
    state: started
    enabled: True

- name: Include cadvisor
  include: cadvisor.yml
  when: install_cadvisor
