---
- name: restart docker
  service:
    name: docker
    state: restarted

- name: restart docker systemd
  systemd:
    name: docker
    state: restarted
    daemon_reload: True

- name: reenable cadvisor service
  command: systemctl reenable cadvisor.service

- name: reinit cadvisor
  command: initctl reload-configuration

- name: restart cadvisor
  service:
    name: cadvisor
    state: restarted
